[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--prefix=/dev/null"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"